wireapp/wire-ios-share-engine

- wire-ios-share-engine/SharingSession.swift
* The wrong initializer for `ZMBackendEnvironment` has been used, the `init()` will be marked as `NS_UNAVAILBLE` in a PR to `wire-ios-transport` in order to avoid issues like these.
> User the backend environment stored in the shared user defaults

- wire-ios-share-engine/ZMConversation+Conversation.swift
* Check security level instead of `trusted` property, as there might be participants without any clients.
> Check security level instead of isTrusted property

- wire-ios-share-engine/OperationLoop.swift
- wire-ios-share-engine/Sendable.swift
- wire-ios-share-engine/SharingSession.swift
- wire-ios-share-engine/ZMMessage+Sendable.swift
* Using the shorthand function pointer syntax to assign to a closure can lead to a leak in case self is accessed in the assigned function, as we used this syntactic sugar a lot in the share engine a lot of places had to be modified.
* Insert missing calls to tear down the strategies and the transport session.
> Fix memory leaks

- wire-ios-share-engine.xcodeproj/project.pbxproj
- wire-ios-share-engine/Sendable.swift
- wire-ios-share-engine/SendableBatchObserver.swift
- wire-ios-share-engine/ZMMessage+Sendable.swift
Observing changes on the context was unreliable. This PR uses a safer approach: re-check for changes on EVERY save.
> Simplify observation of changes

- wire-ios-share-engine/OperationLoop.swift
- wire-ios-share-engine/SharingSession.swift
* We were missing the change info from the `syncMOC` and thus were missing updated clients in the main app after discovering them from the share-extension.
> Store save info from both contexts

- wire-ios-share-engine.xcodeproj/project.pbxproj
- wire-ios-share-engine/Sendable.swift
- wire-ios-share-engine/SendableBatchObserver.swift
- wire-ios-share-engine/SharingSession.swift
- wire-ios-share-engine/SharingTarget.swift
- wire-ios-share-engine/StrategyFactory.swift
- wire-ios-share-engine/ZMConversation+Conversation.swift
- wire-ios-share-engine/ZMMessage+Sendable.swift
* Extract the creation of all strategies used in the share extension into a separate class called `StrategyFactory`.
* Add the `LinkPreviewAssetUploadRequestStrategy` to the included strategies.
* Change the `appendTextMessage` method to take an additional parameter specifying if a link preview should be fetched.
* Modify and rename the `deliveryState` property to `isSent`, it now also checks the `linkPreviewState` in the case of a `ZMClientMessage` to avoid the share extension being deallocated before the link preview has been fetched an uploaded.
> Extract strategy creation in separate class, add option to fetch link previews

- wire-ios-share-engine/ZMMessage+Sendable.swift
* Image messages are marked as sent after the response for the preview upload has been received, which leads to the share extension being dismissed prematurely and sporadic failures sending the medium image (depending on the size of the image and the number of clients it is being sent to).
> Only consider asset client message as sent when uploadState is done

- Sources/OperationLoop.swift
- wire-ios-share-engineTests/BaseSharingSessionTests.swift
* Fix a crash happening when trying to call `tearDown` on `MissingClientsRequestStrategy`.
> Only tear down strategies if they respond to the selector

- Sources/SharingSession.swift
- WireShareEngineTests/BaseSharingSessionTests.swift
Share engine was still creating it's caches in `<SharedContainer>/Library/Caches` when now it should create them in `<SharedContainer>/Library/Caches/wire-account-<UUID>/`
> Use new location for caches

- Sources/SharingSession.swift
Share extension creates a file in the caches directory which makes the main app throw an error.
Doesn't create transport session configured for background requests.
The shared container identifier is used in the transport session for background requests
managed by the system. The system will then wake the app up when the request finishes but
we don't use this functionallity at the moment.
> Remove shared container identifier transport session

- Sources/OperationLoop.swift
- Teardown is mandatory on reachability object that is the part of the transport. This causes the crash on dealloc.
> Tear down the transport to avoid the crash

- Sources/SharingSession.swift
I added the `isLocalAuthenticationGranted` flag to `SharingSession`, in order to remember if the user was already authenticated via `LocalAuthentication` during the current session. 
Needs releases with:
> Added the flag "isLocalAuthenticationGranted"

- Sources/SharingSession.swift
Removed `isLocalAuthenticationGranted` flag. See https://github.com/wireapp/wire-ios/pull/1613 for further details. Needs release with https://github.com/wireapp/wire-ios/pull/1613.
> Removed isLocalAuthenticationGranted flag

- Sources/SharingSession.swift
The `SharingSession` is re-created in share extension when user is selecting the other account.
`tearDown()` method of `SharingSession` was calling `StorageStack.reset()`.
The implementation of `StorageStack.reset()` has changed in the way that it is turning down the managed object context directory: `StorageStack.currentStack?.managedObjectContextDirectory?.tearDown()`.
Generally, the storage stack must not be torn down when switching the accounts, so now we are going to call `StorageStack.reset()` when the share extension is torn down.
> Do not tear down the storage stack in sharing session

- Sources/SharingSession.swift
There was no good reason to create backend environment in the initializer. It makes it more convenient to simply take it as parameter.
> Injecting backend environment

- Sources/SharingSession.swift
From inside share extension we need a method to check if account has existing cookie and is authenticated.
Added identical method that is available in SyncEngine.
> Added a way to check if account is authenticated

- Sources/Conversation.swift
- Sources/ZMConversation+Conversation.swift
We need to expose the security level of the conversation in order to display the correct verified shield.
> Expose the security level of the conversation

- Sources/WireShareEngine.h
- WireShareEngine.xcodeproj/project.pbxproj
Fix Carthage issue for `***  Skipped installing wire-ios-share-engine.framework binary due to the error:
"Unable to determine framework Swift version: Could not derive version from header file."
`
> undo removing WireShareEngine.h 

- WireShareEngine.xcodeproj/project.pbxproj
undo override `SWIFT_OBJC_INTERFACE_HEADER_NAME`
> Fix: carthage swift version issue

- Sources/SharingSession+EncryptionAtRest.swift
- Sources/SharingSession.swift
- WireShareEngine.xcodeproj/project.pbxproj
- WireShareEngineTests/BaseSharingSessionTests.swift
- WireShareEngineTests/SharingSessionTests+EncryptionAtRest.swift
Expose a public API in the `SharingSession` for encryption at rest. This API will be used by the share extension to ask the user to authenticate if the database is locked.
> [Feature] Add support for EAR in the SharingSession

- WireShareEngine.xcodeproj/project.pbxproj
----
- The **PR Title**
- The **PR Description**
----
By default, Xcode can't find any packages installed by homebrew on Apple Silicon Macs, since they're now installed to a different location that isn't on the default `$PATH (/opt/homebrew/bin/`, rather than `/usr/local/bin`).
Workaround: explicitly add this location to `$PATH` before attempting to run swiftlint.
----
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.
> chore: SwiftLint, add support for Apple Silicon brew directory
